### ISSUE TITLE
Adjust footprint of capacitors

### ISSUE THREAD

**Issue by liquiddandruff** [SFUSatClub/OBC_Hardware_v1#2]
From yesterday's assembly, the distance between each pad for the capacitors we used seems a bit too far; perhaps could be adjusted slightly (closer) for future revision.

**Comment by richarthurs** [comment]
Original pad spacing was 0.25mm (pad edge-centerline). Data sheet says 0.3mm which is crazy. Changed to 0.225mm. 

http://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM155R71H103KA88-01.pdf
