### ISSUE TITLE
Add jumper to USB 5V0 line

### ISSUE THREAD

**Issue by Alenux55** [SFUSatClub/OBC_Hardware_v1#3]
Currently USB 5V0 line is connected directly to PC-104 connector 5V0 pin, which would contend with the 5V0 coming from the power board.

Add a connector (something like a [0.1" two-pin header](https://www.digikey.ca/products/en?keywords=S1011EC-02-ND)) so the USB power can be disabled.

**Comment by richarthurs** [comment]
fixed in e8887260e9f13a514a2e4212145bce58cf511cf9
